# https://aka.ms/yaml

trigger:
  - master

variables:
    regression: 1

jobs:
  - job: build_ubuntu_2004
    displayName: Ubuntu 2004
    pool:
      vmImage: 'Ubuntu-20.04'
    timeoutInMinutes: 120
    strategy:
      matrix:
        avx2:
          SIMD: 'AVX2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: RelWithDebInfo
        # sse41:
        #   SIMD: 'SSE4_1'
        #   STATIC: 1
        #   MPI: 0
        #   BUILD_TYPE: RelWithDebInfo
        sse2:
          SIMD: 'SSE2'
          STATIC: 1
          MPI: 0
          BUILD_TYPE: RelWithDebInfo
        avx2_mpi:
          SIMD: 'AVX2'
          STATIC: 0
          MPI: 1
          BUILD_TYPE: RelWithDebInfo
        asan:
          SIMD: 'AVX2'
          STATIC: 0
          MPI: 0
          BUILD_TYPE: ASanOpt
    steps:
      - checkout: self
        submodules: true
      - script: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11 libgcc-11-dev rustc cargo build-essential
        displayName: Install newer GCC
      - script: |
          sudo apt-get update
          sudo apt-get -y install mpi-default-dev mpi-default-bin
        displayName: Install Dependencies
        condition: eq(variables['MPI'], 1)
      - script: |
          mkdir build && cd build
          export CC=gcc-11 ; export CXX=g++-11
          if [ "${STATIC}" -eq "1" ]; then
              cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_SHARED_LIBS=OFF \
                -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc \
                -static-libstdc++" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
                -DENABLE_WERROR=0 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          else
              cmake -DHAVE_SANITIZER=1 -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
                -DENABLE_WERROR=0 -DHAVE_${SIMD}=1 -DHAVE_MPI=${MPI} ..
          fi

          make -j $(nproc --all)
        displayName: Build
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          ./util/Metabuli-regression/run_regression.sh ./build/src/metabuli examples 
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        condition: eq(variables['STATIC'], 1)
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/src/metabuli
          artifactName: metabuli-linux-$(SIMD)

  - job: build_ubuntu_cross_2004
    displayName: Ubuntu 2004 Cross-Compile
    pool:
      vmImage: 'Ubuntu-20.04'
    strategy:
      matrix:
        arm64:
          SIMD: ARM8
          ARCH: arm64
          CPREF: aarch64
    steps:
      - script: |
          sudo dpkg --add-architecture $ARCH
          cat << HEREDOC | sudo tee /etc/apt/sources.list
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ focal main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ focal-updates main universe multiverse
          deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu/ focal-backports main universe multiverse
          deb [arch=amd64,i386] http://security.ubuntu.com/ubuntu/ focal-security main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ focal main  universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ focal-backports main universe multiverse
          deb [arch=$ARCH] http://ports.ubuntu.com/ubuntu-ports/ focal-security main universe multiverse
          HEREDOC
          sudo apt-get update
          sudo apt-get -y install -o APT::Immediate-Configure=false crossbuild-essential-$ARCH zlib1g-dev:$ARCH libbz2-dev:$ARCH
          rustup target add ${CPREF}-unknown-linux-gnu
        displayName: Install Toolchain
      - script: |
          mkdir build && cd build
          CC=${CPREF}-linux-gnu-gcc CXX=${CPREF}-linux-gnu-g++ \
           cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DHAVE_TESTS=1 \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="-static -static-libgcc \
            -static-libstdc++" -DCMAKE_FIND_LIBRARY_SUFFIXES=".a" \
            -DRust_CARGO_TARGET=${CPREF}-unknown-linux-gnu \
            -DENABLE_WERROR=0 -DHAVE_${SIMD}=1 ..
          make -j $(nproc --all)
        displayName: Build Metabuli
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/src/metabuli
          artifactName: metabuli-linux-$(SIMD)

  - job: build_macos
    displayName: macOS
    pool:
      vmImage: 'macos-latest'
    steps:
      - checkout: self
        submodules: true
      - script: |
          rustup update
          rustup target install x86_64-apple-darwin
          rustup target install aarch64-apple-darwin
        displayName: Install Rust Toolchain
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          ./util/build_osx.sh . build metabuli
        displayName: Build Metabuli
      - script: |
          cd ${BUILD_SOURCESDIRECTORY}
          ./util/Metabuli-regression/run_regression.sh ./build/metabuli examples 
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)/build/metabuli
          artifactName: metabuli-darwin-universal
          
  - job: build_windows
    displayName: Windows
    pool:
      vmImage: 'windows-2019'
    variables:
      CYGWIN_ROOT: $(System.Workfolder)\cygwin
      CYGWIN_MIRROR: http://cygwin.mirror.constant.com
    timeoutInMinutes: 120
    steps:
      - powershell: git config --global core.autocrlf false
        displayName: core.autocrlf false
      - checkout: self
        submodules: true
      - script: |
          rmdir /s /q C:\Strawberry
        displayName: Remove Strawberry Perl (Conflict with Cygwin)
      - script: |
          choco install cygwin --params="/InstallDir:%CYGWIN_ROOT%"
        displayName: Install Cygwin
      - script: |
          %CYGWIN_ROOT%\cygwinsetup.exe -qnNdO -R "%CYGWIN_ROOT%" -s "%CYGWIN_MIRROR%" -g -P ^
          bash,^
          xxd,^
          cmake,^
          make,^
          gcc-core,^
          gcc-g++,^
          zlib-devel,^
          libbz2-devel,^
          busybox-standalone,^
          git,^
          binutils,^
          wget,^
          bc
        displayName: Install Dependencies
      - script: |
          %CYGWIN_ROOT%\bin\bash.exe -cl "${BUILD_SOURCESDIRECTORY}/util/build_windows.sh $(cygpath ${BUILD_SOURCESDIRECTORY}) $(cygpath ${BUILD_SOURCESDIRECTORY}/build)"
        displayName: Build Metabuli
      - task: "ArchiveFiles@2"
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)\build\metabuli
          archiveFile: $(Build.SourcesDirectory)\metabuli-win64.zip
          includeRootFolder: true
          archiveType: zip
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: $(Build.SourcesDirectory)\metabuli-win64.zip
          artifactName: metabuli-win64
      # - script: |
      #     %BUILD_SOURCESDIRECTORY%\build\metabuli\metabuli.bat version
      #   displayName: Setup Busybox
      - script: |
          %CYGWIN_ROOT%\bin\bash.exe -cl "${BUILD_SOURCESDIRECTORY}/util/Metabuli-regression/run_regression.sh $(cygpath ${BUILD_SOURCESDIRECTORY}/build/build_sse2/src/metabuli.exe) $(cygpath ${BUILD_SOURCESDIRECTORY}/examples)"
        displayName: Run Regression Suite
        condition: eq(variables['regression'], 1)

  - job: upload_artifacts
    displayName: Upload Artifacts
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn:
      - build_macos
      - build_ubuntu_2004
      - build_ubuntu_cross_2004
      - build_windows
    steps:
      - script: |
          cd "${BUILD_SOURCESDIRECTORY}"
          mkdir metabuli
          cp -f README.md LICENCE.md metabuli
          mkdir metabuli/bin
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metabuli-darwin-universal
          targetPath: $(Build.SourcesDirectory)/metabuli/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
          archiveFile: $(Build.SourcesDirectory)/metabuli-osx-universal.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metabuli-win64
          targetPath: $(Build.SourcesDirectory)
      - script: |
          unzip "${BUILD_SOURCESDIRECTORY}/metabuli-win64.zip"
          chmod +x metabuli/metabuli.bat metabuli/bin/*
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
          archiveFile: $(Build.SourcesDirectory)/metabuli-win64.zip
          includeRootFolder: true
          archiveType: zip
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metabuli-linux-SSE2
          targetPath: $(Build.SourcesDirectory)/metabuli/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
          archiveFile: $(Build.SourcesDirectory)/metabuli-linux-sse2.tar.gz
          includeRootFolder: true
          archiveType: tar
      # - task: DownloadPipelineArtifact@1
      #   inputs:
      #     artifactName: metabuli-linux-SSE4_1
      #     targetPath: $(Build.SourcesDirectory)/metabuli/bin
      # - script:
      #     chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      # - task: ArchiveFiles@2
      #   inputs:
      #     rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
      #     archiveFile: $(Build.SourcesDirectory)/metabuli-linux-sse41.tar.gz
      #     includeRootFolder: true
      #     archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metabuli-linux-AVX2
          targetPath: $(Build.SourcesDirectory)/metabuli/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
          archiveFile: $(Build.SourcesDirectory)/metabuli-linux-avx2.tar.gz
          includeRootFolder: true
          archiveType: tar
      - task: DownloadPipelineArtifact@1
        inputs:
          artifactName: metabuli-linux-ARM8
          targetPath: $(Build.SourcesDirectory)/metabuli/bin
      - script:
          chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
          archiveFile: $(Build.SourcesDirectory)/metabuli-linux-arm64.tar.gz
          includeRootFolder: true
          archiveType: tar
      # - task: DownloadPipelineArtifact@1
      #   inputs:
      #     artifactName: metabuli-linux-POWER8
      #     targetPath: $(Build.SourcesDirectory)/metabuli/bin
      # - script:
      #     chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      # - task: ArchiveFiles@2
      #   inputs:
      #     rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
      #     archiveFile: $(Build.SourcesDirectory)/metabuli-linux-ppc64le-POWER8.tar.gz
      #     includeRootFolder: true
      #     archiveType: tar
      # - task: DownloadPipelineArtifact@1
      #   inputs:
      #     artifactName: metabuli-linux-POWER9
      #     targetPath: $(Build.SourcesDirectory)/metabuli/bin
      # - script:
      #     chmod +x "${BUILD_SOURCESDIRECTORY}/metabuli/bin/metabuli"
      # - task: ArchiveFiles@2
      #   inputs:
      #     rootFolderOrFile: $(Build.SourcesDirectory)/metabuli
      #     archiveFile: $(Build.SourcesDirectory)/metabuli-linux-ppc64le-POWER9.tar.gz
      #     includeRootFolder: true
      #     archiveType: tar
      - task: DownloadSecureFile@1
        inputs:
          secureFile: azure_upload_metabuli
        displayName: Get Deployment Key
      - script: |
          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
          ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
          cd "${BUILD_SOURCESDIRECTORY}"
          # disabled:metabuli-linux-sse41.tar.gz metabuli-linux-ppc64le-POWER8.tar.gz metabuli-linux-ppc64le-POWER9.tar.gz
          ssh-keygen -Y sign -f ~/.ssh/id_rsa -n file \
             metabuli-osx-universal.tar.gz \
             metabuli-linux-sse2.tar.gz \
             metabuli-linux-avx2.tar.gz \
             metabuli-linux-arm64.tar.gz \
             metabuli-win64.zip
          curl --retry 5 --retry-all-errors -X POST \
            -F file[]=@metabuli-osx-universal.tar.gz -F signature[]=@metabuli-osx-universal.tar.gz.sig \
            -F file[]=@metabuli-linux-sse2.tar.gz -F signature[]=@metabuli-linux-sse2.tar.gz.sig \
            -F file[]=@metabuli-linux-avx2.tar.gz -F signature[]=@metabuli-linux-avx2.tar.gz.sig \
            -F file[]=@metabuli-linux-arm64.tar.gz -F signature[]=@metabuli-linux-arm64.tar.gz.sig \
            -F file[]=@metabuli-win64.zip  -F signature[]=@metabuli-win64.zip.sig \
            -F identifier="metabuli" -F directory="${BUILD_SOURCEVERSION}" \
              https://mmseqs.com/upload
